### ISSUE TITLE
Gradle not resolving

### ISSUE THREAD

**Issue by Arkanayan** [deano2390/MaterialShowcaseView#86]
Gradle couldn't find the library. With or without aar nothing works. There may be problem with jitpack.io

**Comment by Arkanayan** [comment]
Solved by updating gradle to version 2.12

**Comment by TPeterW** [comment]
I still have the same problem, I've tried gradle version 12,14 and all other tricks. Should I turn to source code now?
